### PR TITLE
Fix some lint warnings

### PR DESCRIPTION
**Pull request by tzm41**
This commit improves lint score from 9.55 to 9.64.

Notes:
Removed `memoized` class, as that doesn't seem to get used in either `silk` or `silk_ext`. I believe `functools` has `@cached_property` decorator that does the same thing since Python 3.2, so this is a relic of Python 2 code.

### CODE REVIEW

**Comment by tzm41** [comment]
@googlebot I signed it!

**Comment by ctan-g** [comment]
Thanks for contributing, Colin!

-- Colin

**Review by qilinkang — APPROVED** [review]
LGTM

**Review by priyankaCh22 — APPROVED** [review]
LGTM

**Review by jwhui — APPROVED** [review]

**Pull request merged**
